import localFont from "next/font/local";
import "../globals.css";
import SideBar from "@/components/Common/SideBar";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen bg-backgroundGreen">
        <SideBar/>
        <div className="bg-white grow rounded-3xl pl-10 pr-8 py-10 overflow-y-scroll">{children}</div>
        </div>
        
      </body>
    </html>
  );
}
